"""Añadir campos photo, description y price a Supply

Revision ID: 23d0b4fc1231
Revises: add_profile_photo
Create Date: 2025-01-11 10:30:24.137839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d0b4fc1231'
down_revision = 'add_profile_photo'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('description')
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
